# fly.toml app configuration file generated for nodejs-api-topup on 2024-02-29T23:05:28+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodejs-api-topup'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
